# Setup
title:               Fevzi Ömür Tekin
tagline:             'Mobile Application Developer, Sports Auidence'
description:         'I’m mainly interested in Mobile Application Development, Kotlin, Flutter, Java, Android Library, Book. For random bits follow me on Twitter/Instagram/Medium/Goodreads : @fevziomurtekin. For more info about my professional career, visit my <a href= "https://www.linkedin.com/in/fevziomurtekin"> Linkedin profile</a>'
url:                 https://fevziomurtekin.github.io
baseurl:             ''
paginate:            5
github.repo:         https://github.com/fevziomurtekin
permalink:           pretty

# About/contact
author:
  name:              Fevzi Ömür Tekin
  url:               https://twitter.com/fevziomurtekin
  email:             fevziomurtekin@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-3C1ZZ55LK4
