# Setup
title:               Fevzi Ömür Tekin website
tagline:             'A Jekyll theme'
description:         ''
url:                 fevziomurtekin.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Fevzi Ömür Tekin
  url:               https://twitter.com/fevziomurtekin
  email:             fevziomurtekin@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-3C1ZZ55LK4
